name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.2'

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install Dependencies
      run: composer install

    - name: Generate key
      run: php artisan key:generate

    - name: Generate database file
      run: touch database/database.sqlite

    - name: Migrate database
      run: php artisan migrate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Run lint
      run: make lint

    - name: Run tests
      run: make test
